initial PR
che-dockerfiles/che-sidecar-bazel pull request #3
Opened 2020-06-25 06:02 UTC by gattytto

Signed-off-by: Esteban Mañaricua <emanaricua@gmail.com>

2020-06-25 18:23 UTC, ericwill requested changes
Please see my comments on the README about the repo layout. We also need the following files:
* `VERSION`
* `PLATFORMS`

You can look at [this repo](https://github.com/che-dockerfiles/che-sidecar-openshift-connector) for inspiration.

2020-06-25 18:23 UTC, ericwill commented on README.md
> - - linux/amd64
This was here for a reason. :) we are not using the branch system any longer, the latest version lives on the master branch, after that old versions get pushed to their own branches. You can take a look at the [openshift sidecar repo](https://github.com/che-dockerfiles/che-sidecar-openshift-connector) for an example.

2020-06-25 18:23 UTC, ericwill commented on etc/entrypoint.sh
> +#!/bin/sh
Make sure `chmod +x` this file otherwise we will have failures.

2020-06-25 18:23 UTC, ericwill commented on Dockerfile
> +# Copyright (c) 2019 Red Hat, Inc.
Copyright year

2020-06-25 18:23 UTC, ericwill commented on Dockerfile
> +FROM quay.io/buildah/stable:v1.14.3
Is there enough overlap to justify using the `che-sidecar-kubernetes-tooling` image as a base?

2020-06-26 16:31 UTC, gattytto commented
@ericwill ok I'll make a new pr based on the changes you mentioned

2020-06-26 16:31 UTC, closed without merging